### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [siggel/coordinatejoker#92]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7992460763#L285

as this lib is not FLOSS: https://github.com/siggel/coordinatejoker/blob/1.4.35/app/build.gradle#L84

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d40fda01277ab9a913a2a6a50592282cab187931

**Comment by siggel** [comment]
Any F-Droid pros here, that can give a hint what alternative library to use instead of com.google.android.gms:oss-licenses-plugin/com.google.android.gms:play-services-oss-licenses? A buildtime toolset for generating a "readable SBOM" (e.g. html page with links) would be sufficient for my purpose to replace the Google-generated license overview by displaying a build-time-generatred html file instead when building for F-Droid.

**Comment by licaon-kter** [comment]
Sure: https://gitlab.com/-/snippets/1896503#license-dialogs

**Comment by licaon-kter** [comment]
Fastlane is updated when F-Droid builds and publishes a new version.

We can test whatever you want before tagging, fyi

**Comment by siggel** [comment]
should be solved in v 1.4.38

**Comment by licaon-kter** [comment]
Thanks

**Comment by licaon-kter** [comment]
@siggel just a fyi, since https://github.com/siggel/coordinatejoker/commit/7751edbe3eb4d2ec0703bdd10998dcffecfa3a6b#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R18 versionName is not auodetected ok since the check bot does not resolve functions

is there a NEED to have versionCode at the end? will there be an `1.4.40` or `1.4.50` etc?

**Comment by siggel** [comment]
I'll switch back to setting it by hand to 1.4.40 etc. I simply had not been aware of that restriction.

**Comment by siggel** [comment]
Published 1.4.40 for fixing it
